### ISSUE TITLE
Serverless SSR Errors

### ISSUE THREAD

**Issue by sirwesley** [Enngage/ngx-captcha#10]
Fairly new to Angular 6, but when attempting to use serverless SSR for SEO purposes, I'm getting the following errors: 

ERROR ReferenceError: document is not defined
    at InvisibleReCaptchaComponent.module.exports.BaseReCaptchaComponent.ensureCaptchaElem 

ReferenceError: window is not defined
    at InvisibleReCaptchaComponent.module.exports.BaseReCaptchaComponent.ngOnDestroy

Maybe a [disabled] property could used until the actual Angular App loads?  Or simply not attempt to do anything unless 'document' and 'window' are defined?  I'm open to other suggestions as well. 

Let me know if you need more details.

**Comment by sirwesley** [comment]
Solved the problem by wrapping component in ngIf div
Example: 
component.html:
```
<div *ngIf="windowDefined">
     <ngx-invisible-recaptcha required
                    [type]="'image'"
                    [badge]="'bottomright'"
                    (load)="handleLoad()"
                    (resolved)="resolved($event)"
                    (success)="resolved($event)">
    </ngx-invisible-recaptcha>
</div>
```
component.ts:

```
ngOnInit() {
        if ( typeof window !== undefined) {
            this.windowDefined = true;
        }
}
```

**Comment by cyrep** [comment]
ts:
constructor(@Inject(PLATFORM_ID) private platformId: any) {
  this.isBrowser = isPlatformBrowser(this.platformId);
}

html:
<ng-container *ngIf="uiService.isBrowser">
   <ngx-invisible-recaptcha ...></ngx-invisible-recaptcha>
</ng-container>
