### ISSUE TITLE
Captcha V3 not working with aot build in Angular 8

### ISSUE THREAD

**Issue by usmansic** [Enngage/ngx-captcha#105]
getting this error while doing aot build please check

version 9.0.1 

ERROR in Directive BaseReCaptchaComponent in  C:/Users/git/node_modules/ngx-captcha/ngx-captcha.d.ts has no selector, please add it!
Cannot determine the module for class BaseReCaptchaComponent in C:/Users/git/node_modules/ngx-captcha/ngx-captcha.d.ts! Add BaseReCaptchaComponent to the NgModule to fix it.

**Comment by Enngage** [comment]
Hi @usmansic ,

Angular 8 is not even officially supported (https://angular.io/guide/releases) and I don't plan on making any changes here either. However, I can tell you that this library worked perfectly fine in Angular 8. Maybe you just need to use older version or reinstall your node_modules.

**Comment by usmansic** [comment]
Hi Enngage,
Thanks for your reply
It is working fine with the version 8.0.1
