### ISSUE TITLE
Captcha element with id 'ngx_captcha_id_xxxx' was not found

### ISSUE THREAD

**Issue by Angele91** [Enngage/ngx-captcha#11]
I'm having some trouble trying to integrate this component into my ng5 application. 

The first time I used it, it was working fine. I changed the siteKey in the module parameters when importing it to my main module, and stopped working, showing this error: 

`aptcha element with id 'ngx_captcha_id_8486' was not found
    at ReCaptcha2Component.push../node_modules/ngx-captcha/fesm5/ngx-captcha.js.BaseReCaptchaComponent.ensureCaptchaElem (ngx-captcha.js:225)
    at ReCaptcha2Component.push../node_modules/ngx-captcha/fesm5/ngx-captcha.js.BaseReCaptchaComponent.createAndSetCaptchaElem (ngx-captcha.js:414)
    at ReCaptcha2Component.push../node_modules/ngx-captcha/fesm5/ngx-captcha.js.BaseReCaptchaComponent.setupComponent (ngx-captcha.js:353)
    at ReCaptcha2Component.push../node_modules/ngx-captcha/fesm5/ngx-captcha.js.BaseReCaptchaComponent.ngOnChanges (ngx-captcha.js:132)
    at ReCaptcha2Component.push../node_modules/ngx-captcha/fesm5/ngx-captcha.js.ReCaptcha2Component.ngOnChanges (ngx-captcha.js:487)
    at checkAndUpdateDirectiveInline (core.js:12347)
    at checkAndUpdateNodeInline (core.js:13878)
    at checkAndUpdateNode (core.js:13821)
    at debugCheckAndUpdateNode (core.js:14714)
    at debugCheckDirectivesFn (core.js:14655)`

Here is some data about my implementation:

signup.component.html: 
`
...
<ngx-recaptcha2 #captchaElem [size]="'normal'" [hl]="'es'" [theme]="'light'" [type]="'image'" 
                      (expire)="handleExpire()" 
                      (load)="handleLoad()"
                      (success)="handleSuccess($event)">
</ngx-recaptcha2>
...
`

session.module.ts: 
`
...
imports: [
    CommonModule,
    RouterModule.forChild(SessionRoutes),
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatCheckboxModule,
    MatButtonModule,
    FlexLayoutModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    NgxCaptchaModule.forRoot({
      reCaptcha2SiteKey: 'xxxx'
    })
  ],
...
`

Here are my deps

 "dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "5.2.0",
    "@angular/cdk": "5.1.0",
    "@angular/common": "5.2.0",
    "@angular/compiler": "5.2.0",
    "@angular/core": "5.2.0",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "5.2.0",
    "@angular/http": "5.2.0",
    "@angular/material": "5.1.0",
    "@angular/platform-browser": "5.2.0",
    "@angular/platform-browser-dynamic": "5.2.0",
    "@angular/router": "5.2.0",
    "@asymmetrik/ngx-leaflet": "3.0.1",
    "@ngx-loading-bar/router": "^1.1.0",
    "@ngx-translate/core": "9.1.1",
    "@ngx-translate/http-loader": "2.0.1",
    "@swimlane/ngx-datatable": "11.1.7",
    "angular-calendar": "0.23.2",
    "angular-tree-component": "7.0.1",
    "angular5-recaptcha": "0.0.2",
    "chart.js": "2.7.1",
    "core-js": "2.5.3",
    "d3": "4.12.2",
    "dragula": "3.7.2",
    "hammerjs": "2.0.8",
    "intl": "^1.2.5",
    "leaflet": "1.3.0",
    "moment": "2.20.1",
    "ng2-charts": "1.6.0",
    "ng2-completer": "^2.0.8",
    "ng2-dragula": "1.5.0",
    "ng2-file-upload": "1.3.0",
    "ng2-smart-table": "^1.3.5",
    "ng2-validation": "4.2.0",
    "ngx-captcha": "^3.1.0",
    "ngx-perfect-scrollbar": "5.3.1",
    "ngx-quill": "2.0.4",
    "ngx-store": "^2.0.0",
    "rxjs": "5.5.6",
    "screenfull": "3.3.2",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "5.2.0",
    "@angular/language-service": "5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3",
    "@angular-devkit/build-angular": "~0.6.8"
  }

**Comment by Enngage** [comment]
Hi, this doesn't appear to be related to site keys. Rather it seems there is some sort of issue within your code - its quite difficult to manage captcha in Angular and thus each captcha iteration has its own id stored like '`ngx_captcha_id_x`' where 'x' is the number of captcha on that page starting from 1 (or 0 - cant remember). Since you have `ngx_captcha_id_8486` it would mean that your captcha has been reloaded at least 8486 times on that same page! 

If you feel this is a bug, please reproduce on stackblitz or on the fork of this library. Otherwise, I feel think you should double check your code.

**Comment by darrynhoskingluna** [comment]
I also get this error, it happens when you nest the ngx-captcha inside a form inside a mat-stepper.

Here is a link to a stackblitz showing the error. 
https://stackblitz.com/edit/angular-oxg9mt


as a work around for now i am adding the ngx-captcha inside its own form and manually validating this form on submit of the forms within the mat-stepper

**Comment by RudyAlmeida** [comment]
Had the same isue, in my case it was inside a modal, solved the problem calling initConfig() only when modal as called.
