### ISSUE TITLE
resizing input

### ISSUE THREAD

**Issue by alexfarrugia** [Enngage/ngx-captcha#114]
Hi is there any easy to resize the element which is generated? I want to avoid implementing a directive which stays adding classes to some of the elements in the component? maybe by passing a class to the component or so? All i want is to have it resize to 100% of its parent container.

thanks

**Comment by Enngage** [comment]
I'm not aware of any configuration on Google's side to do this. Maybe you can try overriding the styles of rendered recaptcha, but it's not something this library would do.
