### ISSUE TITLE
Getting error in prod build

### ISSUE THREAD

**Issue by varaprasadreddy9676** [Enngage/ngx-captcha#115]
ERROR in : Directive BaseReCaptchaComponent in C:/Users/varap/client/node_modules/ngx-captcha/ngx-captcha.d.ts has no selector, please add it!
: Cannot determine the module for class BaseReCaptchaComponent in C:/Users/varap/client/node_modules/ngx-captcha/ngx-captcha.d.ts! Add BaseReCaptchaComponent to the NgModule to fix it.

[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build:production exited with exit code 1.

**Comment by Enngage** [comment]
https://github.com/Enngage/ngx-captcha/issues/105
