### ISSUE TITLE
Support Angular 12

### ISSUE THREAD

**Issue by delciopolanco** [Enngage/ngx-captcha#116]
Hi Dear,

I'm not able to use ngx-captcha with  angular 12.

see console error when trying to download.

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: front-end@0.0.0
npm ERR! Found: @angular/common@12.0.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.0" from ngx-captcha@9.0.1
npm ERR! node_modules/ngx-captcha
npm ERR!   ngx-captcha@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/bhdleon/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bhdleon/.npm/_logs/2021-06-28T16_35_02_798Z-debug.log`

**Comment by Enngage** [comment]
Try removing package-lock, delete your node_modules, run `npm cache verify` and install your packages again.
