### ISSUE TITLE
has anyone tried this component on Android Phone Chrome? The images are not popped up when I click checkbox

### ISSUE THREAD

**Issue by kxying-kk** [Enngage/ngx-captcha#120]

**Comment by blathersbugs** [comment]
Recaptcha won't make you solve a puzzle every time, you can adjust the settings in the admin console to make it more aggressive, but there is no way to make it always trigger.  If Google's algorithm doesn't think you are a bot, you won't be challenged.  If the checkbox is there at all, it is PROBABLY working.
