### ISSUE TITLE
how to use firebase otp verifier

### ISSUE THREAD

**Issue by devgene** [Enngage/ngx-captcha#124]
I need to use this captcha for window.recaptchaVerifier = new firebase.auth.RecaptchaVerifier

**Comment by Enngage** [comment]
I'm not familiar with that. What exactly should this component do or implement?

**Comment by devgene** [comment]
to implement, I want to add this firebase RecaptchaVerifier to send mobile otp

**Comment by Enngage** [comment]
what does that mean for this library?

**Comment by devgene** [comment]
Because am using firebase library for otp. It gives from captcha

Can i use this captcha instead of that

**Comment by Enngage** [comment]
I'm sorry, but I don't know what that means.. Maybe try contacting firebase or captcha support, because this library is built on top of google captcha API (https://developers.google.com/recaptcha/docs/display)
