### ISSUE TITLE
Versioning guidance

### ISSUE THREAD

**Issue by tleperou** [Enngage/ngx-captcha#143]
Could someone help me understand the versioning logic of the package -- which I have to say, this package is great !

I struggle so much to figure out the version to pick. I have to maintain a bunch of different versions of Angular's project. Contributors and users' guidance is welcome :pray: 

Thanks

**Comment by Enngage** [comment]
Hi @tleperou ,

There is really no logic, sorry :) I would just recommend to use the latest version... it targets Angular 14, but it works well in older versions as well.

**Comment by tleperou** [comment]
Noted, thanks.

I'll go with the latest.

:ok_hand:
