### ISSUE TITLE
Compatibility issue for Angular 15

### ISSUE THREAD

**Issue by masollano** [Enngage/ngx-captcha#146]
@Enngage 
I think there's an issue for angular 15 compatibility

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular/common@15.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^15.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0 || ^14.0.0" from ngx-captcha@12.0.2
npm ERR! node_modules/ngx-captcha
npm ERR!   ngx-captcha@"*" from the root project`

**Comment by ismcagdas** [comment]
I had the same problem. Is it possible to release a new version which supports Angular 15 ?

**Comment by andreyjkee** [comment]
@Enngage please update dependencies for angular v15 compatibility

**Comment by Enngage** [comment]
Done
