### ISSUE TITLE
Provide example with standalone form option

### ISSUE THREAD

**Issue by Enngage** [Enngage/ngx-captcha#17]
We should include an example with standalone form initialization.

**Comment by Enngage** [comment]
@danielreiser, do you think you could provide an example of this? I wasn't able to make it work on my end.

**Comment by danielreiser** [comment]
Sure. I'am on vacation though and will only be able to do that in the beginning of september.

**Comment by Bidthedog** [comment]
Not been able to get 5.0.4 working with standalone forms - I upgraded an implementation from 2.2.1 and it now seems to *expect* the Reactive Forms module to function. Is this right?

When I do get it working, I get an error that I *think* is telling me I need to set up a FormGroup?

StaticInjectorError(AppBrowserModule)[NgControlStatus -> NgControl]
No provider for NgControl

I've downgraded back to 2.2.1 for now as that's the last version I know was working for me.
