### ISSUE TITLE
Expired captcha cannot be solved again

### ISSUE THREAD

**Issue by milenyordanov** [Enngage/ngx-captcha#18]
Steps to reproduce:
1) Go to https://enngage.github.io/ngx-captcha/
2) Solve captcha
3) Wait 1-2 minutes till the captcha expire
4) Try to solve the captcha again. It is not possible. The spinner keeps spinning. The JS Console logs an error: "Uncaught (in promise) Request timed out."

If I do the same steps on https://www.google.com/recaptcha/api2/demo then everything works fine.

**Comment by Enngage** [comment]
Thanks for letting me know. Can you try `4.0.1` and see if that helps?
