### ISSUE TITLE
Broken change detection / needs NgZone

### ISSUE THREAD

**Issue by achimha** [Enngage/ngx-captcha#2]
The captcha JS runs outside of the Angular zone which means there is no change detection on the callbacks. It needs to be done like this:

https://github.com/xmaestro/angular2-recaptcha/blob/master/lib/captcha.service.ts

**Comment by Enngage** [comment]
Hi, can you elaborate on why this is needed? We've been using captcha as it is and never encountered an error. We wanted to use the lib you linked, but they have several issues when using in dynamic scenarios and don't for example support changing properties once the lib was loaded. This should be working in this plugin - https://enngage.github.io/ngx-captcha/

If you know of any issue, please do let me know and I'll take a look.

**Comment by achimha** [comment]
You can easily see how it breaks change detection. Define a component variable:

```
public fCaptchaSucceeded = false;
```
Print its value in the component and set it to true when the captcha passes:
```
<ngx-recaptcha2 (success)="fCaptchaSucceeded = true;"></ngx-recaptcha2>
{{ fCaptchaSucceeded }}
```
You will see that the variable output remains `false` even after the `(success)` method is called. This is because it is invoked outside the Angular zone and change detection is skipped.

In order to fix this, you have to make sure the captcha callbacks are called within the Angular zone. This is what `NgZone` allows you to do.

**Comment by Enngage** [comment]
Thanks! I'll test this.

**Comment by achimha** [comment]
Thanks, working now.
