### ISSUE TITLE
Reset recaptcha

### ISSUE THREAD

**Issue by Triplecorpse** [Enngage/ngx-captcha#20]
I would like to validate recaptcha on backend using its response. Unfortunately, on google site I have read:
Each reCAPTCHA user response token can only be verified once. If you need a new token, you will need to call grecaptcha.reset() to ask the end user to verify with reCAPTCHA again.

I need to reset recaptcha but don't find how. Do you have such functionality?

**Comment by Enngage** [comment]
Yeah, you can call `resetCaptcha` method which resides in the component. See example here: https://github.com/Enngage/ngx-captcha/blob/master/demo/src/re-captcha-2-demo.component.ts#L132

**Comment by Triplecorpse** [comment]
Thank you. Think it should added to docs to prevent such misunderstanding.
