### ISSUE TITLE
Not working with template driven form

### ISSUE THREAD

**Issue by achimha** [Enngage/ngx-captcha#22]
Trying to use v5 in a template driven form, I get

```
errorlog.service.ts:26 StaticInjectorError(AppModule)[NgControlStatus -> NgControl]: 
  StaticInjectorError(Platform: core)[NgControlStatus -> NgControl]: 
    NullInjectorError: No provider for NgControl!
```
The `FormsModule` is imported and it's inside a `<form>` element. Your demo only uses reactive forms.

**Comment by achimha** [comment]
Actually it needs a

`ngModel`

attribute to be correctly bound as a forms control. This is a bit confusing because the samples do not use `ngModel` to get the result.

**Comment by nhaancs** [comment]
> Actually it needs a
> 
> `ngModel`
> 
> attribute to be correctly bound as a forms control. This is a bit confusing because the samples do not use `ngModel` to get the result.

that's right, so confusing
