### ISSUE TITLE
Bug: v5.0.0. Building to prod gives me error

### ISSUE THREAD

**Issue by bjornharvold** [Enngage/ngx-captcha#23]
ERROR in : Unexpected value 'undefined' exported by the module 'NgxCaptchaModule in ./node_modules/ngx-captcha/ngx-captcha.d.ts'

**Comment by achimha** [comment]
I can confirm the issue.

**Comment by hamzash750** [comment]
same issue here
**ERROR in : Unexpected value 'undefined' exported by the module 'NgxCaptchaModule in D:/Softwares/Metronic/ProjectBasic/LeBigMarket/node_modules/ngx-captcha/ngx-captcha.d.ts'**

**Comment by Enngage** [comment]
Thats odd.. its working in my other app. How does your NgxCaptchaModule import look like? Have you removed the forRoot as per release notes? See https://github.com/Enngage/ngx-captcha/blob/master/demo/src/demo.module.ts#L20

Also, can you try removing node_modules and installing packages from scratch?

**Comment by Enngage** [comment]
There were some typing issues with production build, try `5.0.1`.. But be also sure to follow new approach with site keys. Let me know how that works. Thanks!

**Comment by achimha** [comment]
5.0.1 shows the same problem

**Comment by achimha** [comment]
The error is gone with 5.0.2 but now I get a lot of warnings like this:

```
37:802-824 "export 'ReCaptchaV3Service' (imported as 'i16') was not found in 'ngx-captcha'

WARNING in ./src/app/lazy/misc/misc.module.ngfactory.js
37:827-844 "export 'ScriptService' (imported as 'i16') was not found in 'ngx-captcha'
```

**Comment by Enngage** [comment]
Could this be related to some specific setup you have? I'm exporting both of these services -> https://github.com/Enngage/ngx-captcha/blob/master/projects/ngx-captcha-lib/src/lib/index.ts

**Comment by achimha** [comment]
I doubt, it's a standard angular-cli setup, large projects, lots of libraries. While the warning is non fatal, the production binary crashes with an infinite recursion when a component using ngx-captcha is invoked.

**Comment by Enngage** [comment]
Can you try clean install? (delete node_modules). I'm also using pretty standard cli setup for the demo app and don't see this issue. Its currently also live on github pages: https://enngage.github.io/ngx-captcha/

I'm really just wondering how this could happen.

**Comment by achimha** [comment]
Tried wiping node_modules before but did it again when going from 5.0.1 to 5.0.2 and this did fix the problem. So it seems to be working now. Thanks for the quick response!

**Comment by Enngage** [comment]
Awesome, glad to hear that!

**Comment by hamzash750** [comment]
Problem solved just change the version     "ngx-captcha": "^5.0.0",  to     "ngx-captcha": "^5.0.2",
Thank you man for saving my time ;)

**Comment by bjornharvold** [comment]
Thank you for the quick turnaround on this one 👍
