### ISSUE TITLE
Parser Error: Unexpected token

### ISSUE THREAD

**Issue by kelzerman** [Enngage/ngx-captcha#29]
I followed the example to the letter, but it keeps giving me a parse error on the sitekey. The test-key or my own key, it doesn't matter.

    Parser Error: Unexpected token 'MYKEY' at column 2 in [MYKEY] in ng:///AppModule/MyComponent.html@19:6 ("

    <ngx-recaptcha2
      [ERROR ->][siteKey]="MYKEY"
      [size]="size"
      [hl]="lang"

What am I doing wrong?

**Comment by Enngage** [comment]
This is Angular way of binding input properties. If you want to bind you would use:

`[siteKey]="nameOfYourPublicProperty"`

and then you have to have your property set in .ts file. 

Or you can use it without binding:

`SiteKey="myCaptchaKey"`

**Comment by kelzerman** [comment]
Got it! Most examples on the internet didn't show the part in the component.ts
