### ISSUE TITLE
.reset() no longer working

### ISSUE THREAD

**Issue by EvD92** [Enngage/ngx-captcha#32]
like title, recaptcha.resetCaptcha(); is no longer working.

using:
"@angular/core": "^7.0.2",
"ngx-captcha": "^6.0.0",

Live examples have the same issue:
https://enngage.github.io/ngx-captcha/

edit:
using .reloadCaptcha() as replacement for now

**Comment by Enngage** [comment]
You're right, I'll have a look in upcoming days
