### ISSUE TITLE
Captcha element with id * was not found"

### ISSUE THREAD

**Issue by MiVvlt** [Enngage/ngx-captcha#34]
I get the following error in my console: 
Captcha element with id 'ngx_captcha_id_4644' was not found"
the captcha doesn't load. 
Strange thing is that when I kill my ng serve process and restart it, it works sometimes.. but most of the time it doesn't.

versions: 
    "@angular/animations": "^6.0.0-rc.5",
    "@angular/cdk": "^6.0.0-rc.5",
    "@angular/common": "^6.0.0-rc.5",
    "@angular/compiler": "^6.0.0-rc.5",
    "@angular/core": "^6.0.0-rc.5",
    "@angular/forms": "^6.0.0-rc.5",
    "@angular/http": "^6.0.0-rc.5",
    "@angular/material": "^6.0.0-rc.5",
    "@angular/platform-browser": "^6.0.0-rc.5",
    "@angular/platform-browser-dynamic": "^6.0.0-rc.5",
    "@angular/router": "^6.0.0-rc.5",

    "ngx-captcha": "^4.0.1",

**Comment by Enngage** [comment]
Can you please try updating to `5.0.4`? If that doesn't help, please provide me with a repro because otherwise I have nothing to go on. You can use e.g. stackblitz which is awesome and incredibly easy to setup.

**Comment by Enngage** [comment]
I'm getting this error when opening your stackblitz example:

```
Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[TranslatePipe -> TranslateService]: 
StaticInjectorError(Platform: core)[TranslatePipe -> TranslateService]: 
NullInjectorError: No provider for TranslateService!
Error: StaticInjectorError(AppModule)[TranslatePipe -> TranslateService]: 
StaticInjectorError(Platform: core)[TranslatePipe -> TranslateService]: 
NullInjectorError: No provider for TranslateService!
```

**Comment by Enngage** [comment]
Closing until valid repro is provided

**Comment by fahrulalwan** [comment]
i have same problem too when refresh page. still getting that error

**Comment by bageren** [comment]
Had the same problem. Solved it by creating the IPayPalConfig object in a timeout:

> ngOnInit() {
>     setTimeout(() => {
>         this.payPalConfig = {
>             **settings**
>         }
>     }, 0);
> }
