### ISSUE TITLE
Nesting captcha inside a form within mat-stepper breaks

### ISSUE THREAD

**Issue by darrynhoskingluna** [Enngage/ngx-captcha#36]
This is perhaps related to https://github.com/Enngage/ngx-captcha/issues/11

When you add a captcha inside a form within a mat-stepper (eg a multi step registration process) the following error is thrown

ERROR Error: Captcha element with id 'ngx_captcha_id_8710' was not found

Changing the HTML and removing the mat-stepper resolves the bug.

Here is a link to a stackblitz showing the error.
https://stackblitz.com/edit/angular-oxg9mt

as a work around for now i am adding the ngx-captcha inside its own form and manually validating this form on submit of the forms within the mat-stepper

**Comment by venoby** [comment]
any updates?

**Comment by MerySantos** [comment]
any updates? :(

**Comment by DVanderstoken** [comment]
same issue

**Comment by DVanderstoken** [comment]
Solved after project update to latests versions :
- angular from 6.0.2 to 8.1.0,
- ngx-captcha from 5.0.4 to 7.0.0

**Comment by slangley** [comment]
I was not able to resolve with new Angular (v8.2) and ngx-captcha v7.0.0 . However leaving this for others who have the same problem, ng-recaptcha works within a Formly form.
