### ISSUE TITLE
Angular test case returns TypeError: _this.reCaptchaApi.render is not a function 

### ISSUE THREAD

**Issue by anupsarkar377** [Enngage/ngx-captcha#38]
**Problem Statement:**  I implemented the ngx-captcha in Angular 6 Reactive forms. The functionality is working fine for me but when I run the test case, my test case fails with the following message  "**TypeError: _this.reCaptchaApi.render is not a function**" in karma.  I implemented the ngx-captcha(visible type) in two component, for both the component functionality is working fine for me, but during test case I am facing above mentioned error.

I tried with the following 

**captcha-test.html**
`<ngx-recaptcha2  #captchaElem [siteKey]="captchaSiteKey" formControlName="captcha"> </ngx-recaptcha2>`

**captca-test.ts**
`export class CaptchaTestComponent implements OnInit {
  validSiteKey: string = environment.validSiteKey;
  captchaExampleForm: FormGroup;
  constructor(private fb: FormBuilder) { }

 ngOnInit() {
    this.captchaExampleForm = this.fb.group({
      captcha: ['', [Validators.required]]
    });
  }
exampleFormSubmit(){
    return false;
   }
}

**captcha-test.spec.ts**
import { async, ComponentFixture, TestBed } from 
"@angular/core/testing";
import { HttpClientModule } from "@angular/common/http";
import { CaptchaTestComponent } from "./captcha-test.component";
import { BrowserAnimationsModule } from "@angular/platform- 
browser/animations";
import { RouterTestingModule } from "@angular/router/testing";
import { MatProgressSpinnerModule, MatFormFieldModule, MatInputModule } 
from "@angular/material";
import { ReactiveFormsModule, FormBuilder } from "@angular/forms";
import { TestConstants } from "src/app/test/constants";
import { NgxCaptchaModule } from "ngx-captcha";

describe("CaptchaTestComponent", () => {
jasmine.getEnv().allowRespy(true);
let fixture: ComponentFixture<CaptchaTestComponent>;

beforeEach(async(function () {
TestBed.configureTestingModule({
  imports: [RouterTestingModule, BrowserAnimationsModule,
    ReactiveFormsModule, HttpClientModule, MatProgressSpinnerModule,
    MatFormFieldModule, MatInputModule, NgxCaptchaModule],
  providers: [FormBuilder
  ],
  declarations: [CaptchaTestComponent]
  }).compileComponents();
}));

 beforeEach(function () {
 fixture = TestBed.createComponent(CaptchaTestComponent);
 this.component = fixture.componentInstance;
this.component.captchaExampleForm.controls["captcha"].setValue(TestConstan ts.validCaptcha); //manually set a string data as input data.

fixture.detectChanges();
});

it("should init component properly", function () {
this.component.ngOnInit();
expect(this.component.captchaExampleForm).toBeDefined();
});

it("should return submit as false when we submit the form", async 
function () {
const result = await this.component.exapmleFormSubmit();
expect(result).toBeFalsy();
    });
  });
`
I am using   "ngx-captcha": "^5.0.4" version with Angular 6.

After try with the above, I am getting **TypeError: _this.reCaptchaApi.render is not a function**
when I am testing in Angular. Please suggest me on this.
Thanks in advance.

**Comment by Enngage** [comment]
This is very likely because the test doesn't have access to global variable where google's reCatpcha api is loaded. At this moment I don't know why or how this happens, but its the way testing works currently. This is the same with all global apis. 

The way you could solve this is by adding google's script to your test environment so that its available. You can see how it was solved in this commit: https://github.com/ArPIHomeSecurity/www/commit/91d81df82a067a736f61e0546a4c4a588259cfe0

**Comment by koladilip** [comment]
I have fixed this by override the component while running test cases: https://stackoverflow.com/questions/54146810/angular-test-case-returns-typeerror-this-recaptchaapi-render-is-not-a-function/54348517#54348517
