### ISSUE TITLE
[siteKey] parameter gets error in Template Driven Form

### ISSUE THREAD

**Issue by foolsama** [Enngage/ngx-captcha#39]
I can't get this to work. I have a sitekey from Google, and want to declare it directly, as your program requests, but I get the following wall of errors:

> compiler.js:2427 Uncaught Error: Template parse errors:
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            <ngx-recaptcha2 class="g-recaptcha" [ERROR ->][siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
                [theme]="light"
                "): ng:///AppModule/RegisterComponent.html@25:48
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
                [ERROR ->][theme]="light"
                (reset)="handleReset()"
                (ready)="handleReady()"
"): ng:///AppModule/RegisterComponent.html@26:16
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
                [theme]="light"
                [ERROR ->](reset)="handleReset()"
                (ready)="handleReady()"
                (load)="handleLoad()""): ng:///AppModule/RegisterComponent.html@27:16
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
                [theme]="light"
                (reset)="handleReset()"
                [ERROR ->](ready)="handleReady()"
                (load)="handleLoad()"
                (success)="handleSucces"): ng:///AppModule/RegisterComponent.html@28:16
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
                (reset)="handleReset()"
                (ready)="handleReady()"
                [ERROR ->](load)="handleLoad()"
                (success)="handleSuccess($event)"
                name="recaptc"): ng:///AppModule/RegisterComponent.html@29:16
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
                (ready)="handleReady()"
                (load)="handleLoad()"
                [ERROR ->](success)="handleSuccess($event)"
                name="recaptcha" required
                ngModel r"): ng:///AppModule/RegisterComponent.html@30:16
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            [ERROR ->]<ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
            "): ng:///AppModule/RegisterComponent.html@25:12, Directive NgControlStatus
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            [ERROR ->]<ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
            "): ng:///AppModule/RegisterComponent.html@25:12, Directive NgControlStatus
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            [ERROR ->]<ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
            "): ng:///AppModule/RegisterComponent.html@25:12, Directive NgControlStatus
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            [ERROR ->]<ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
            "): ng:///AppModule/RegisterComponent.html@25:12, Directive NgControlStatus
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            [ERROR ->]<ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
            "): ng:///AppModule/RegisterComponent.html@25:12, Directive NgControlStatus
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            [ERROR ->]<ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
            "): ng:///AppModule/RegisterComponent.html@25:12, Directive NgControlStatus
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            [ERROR ->]<ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
            "): ng:///AppModule/RegisterComponent.html@25:12, Directive NgControlStatus
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </div>
            <br>
            [ERROR ->]<ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
            "): ng:///AppModule/RegisterComponent.html@25:12, Directive RequiredValidator
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("
            </ngx-recaptcha2>             
    </div>
    [ERROR ->]<mat-card-actions>
        <button type="submit" class="btn btn-primary" style="margin:5px" [disabled"): ng:///AppModule/RegisterComponent.html@35:4, Directive MatCardActions
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("iv>
    <mat-card-actions>
        <button type="submit" class="btn btn-primary" style="margin:5px" [ERROR ->][disabled]="!registerForm.form.valid">Register</button>
        <button class="btn btn-primary" style"): ng:///AppModule/RegisterComponent.html@36:73
Parser Error: Unexpected token 'LeO' at column 2 in [6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr] in ng:///AppModule/RegisterComponent.html@25:48 ("gisterForm.form.valid">Register</button>
        <button class="btn btn-primary" style="margin:5px">[ERROR ->]<a routerLink="/login" style="color: white">Cancel</a></button>
    </mat-card-actions>
</form>

I have tried using parenthesis rather than brackets, tried without anything around it, tried sitekey rather than siteKey. I have tried Google's version, 'data-sitekey' but then it asks for the sitekey parameter.

Here is the HTML
`<form name="registerForm" #registerForm="ngForm" (ngSubmit)="register(model)">
    <div class="form-group">
     ....
     <ngx-recaptcha2 class="g-recaptcha" [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr"
                [theme]="light"
                (reset)="handleReset()"
                (ready)="handleReady()"
                (load)="handleLoad()"
                (success)="handleSuccess($event)"
                name="recaptcha" required
                ngModel recaptcha>
            </ngx-recaptcha2>`

**Comment by Enngage** [comment]
This is not really related to this library. I can see that you are incorrectly using Angular binding syntax (see https://angular.io/guide/template-syntax). 

For example, instead of:

` [siteKey]="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr" `

You should have:

` siteKey="6LeO-4kUAAAAALQ44vKA2QB6K0Zofl2LZO8ULLcr" `

And same goes for other properties that are not binding. Please review Angular docs thoroughly as this is really important to know when developing Angular applications.

**Comment by foolsama** [comment]
Thank you, perhaps you can update your document for template driven forms, since that's what I was using for reference.

**Comment by Enngage** [comment]
You're welcome, I'm glad it helped. Though, I won't really update docs because this is quite basic Angular stuff thats not actually relevant to this library.
