### ISSUE TITLE
reCAPTCHA placeholder element must be an element or id during Unit testing

### ISSUE THREAD

**Issue by rts-cwalker** [Enngage/ngx-captcha#41]
I'm trying to figure this out. Ive seen a few posts about this on Github and SO, but none of the "fixes" have worked for my project. I know this seems to be from Google's script, but Im trying to figure out why i dont see this when running the project and playing around the UI. Nothing shows in the browser console. But when i run unit tests, i see this error pop up, and it seems like each test run, the error pops up on a different component. Even components that dont have the recaptcha even anywhere in them. 

The unit tests are just the default unit tests that come with a component when it is generated. Nothing added to them.

This may not be the correct place, but thought maybe someone knows what exactly to do when they run into this with this component. Thanks for any input!

**Comment by Enngage** [comment]
What do you see if you log `window['grecapcha']` in your tests? Google script registers itself to this global variable and it has to be available. If its not, it may be that the test cleared global variables or they are not accessible. 

you could potentially fix this by adding recaptcha script directly to your index.thml page - or you could add the script to karma's configuration so its aware of it.

**Comment by Vol4Life27** [comment]
I get `LOG: undefined` when running tests. I have placed the script in index.html and karma.conf both and either or and still get same error and log message in all cases. :/

**Comment by rts-cwalker** [comment]
Sorry. Posted from my other Github account on previous post

I get LOG: undefined when running tests. I have placed the script in index.html and karma.conf both and either or and still get same error and log message in all cases. :/

karma.conf:

files: [
    "https://www.google.com/recaptcha/api.js"
]
And in index.html, ive tried adding to head and to end of body with rest of JS files all with same result. Im using Angular 7 if that helps make any difference

**Comment by rts-cwalker** [comment]
Btw, I do wanna say, this is by far the easiest and best implementation of google recaptcha Ive been able to find for use with Angular. Thats why im desperately wanting to figure out this unit testing problem. 👏

**Comment by JakeLardinois** [comment]
Reverting to version ^4.7.0 was the only way I could get around the problem.

It took me  a while to narrow it down to this package, but I was able to verify the issue occurs with ^5.0.0 and ^6.0.0.  What happens is that random tests fail with a "Script error. thrown" both locally using "ng test" and on my CI server.
![image](https://user-images.githubusercontent.com/5565891/52422595-f473ee00-2abb-11e9-9e34-ef30ce58ec88.png)
![image](https://user-images.githubusercontent.com/5565891/52422672-2422f600-2abc-11e9-8acb-e1aa6eb8666b.png)

The odd thing was that sometimes all the tests would succeed!  However, I was able to notice that every time my test would fail, the following error would get logged to the console:

recaptcha__en.js:512 Uncaught Error: reCAPTCHA placeholder element must be an element or id
    at Object.$l [as render] (recaptcha__en.js:512)
    at :9876/_karma_webpack_/webpack:/node_modules/ngx-captcha/fesm5/ngx-captcha.js:211
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:289)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:390)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.run (:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:150)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:17248)
    at ReCaptcha2Component.push../node_modules/ngx-captcha/fesm5/ngx-captcha.js.BaseReCaptchaComponent.renderReCaptcha (:9876/_karma_webpack_/webpack:/node_modules/ngx-captcha/fesm5/ngx-captcha.js:210)
    at ReCaptcha2Component.push../node_modules/ngx-captcha/fesm5/ngx-captcha.js.BaseReCaptchaComponent.onloadCallback (:9876/_karma_webpack_/webpack:/node_modules/ngx-captcha/fesm5/ngx-captcha.js:290)
    at ScriptService.<anonymous> (:9876/_karma_webpack_/webpack:/node_modules/ngx-captcha/fesm5/ngx-captcha.js:263)

Every time my tests succeeded, this error was NOT in the console output. It was ultimately the above console error that allowed me to narrow it down to this package.  I was coming here to log an issue, when I noticed that this one was already created.
My package.json contents are:
![image](https://user-images.githubusercontent.com/5565891/52423169-28034800-2abd-11e9-8987-506a0a93156d.png)

**Comment by JakeLardinois** [comment]
I noticed that the usage of .forRoot stopped being available in version 5 and above. 

Version 4
![image](https://user-images.githubusercontent.com/5565891/52423368-8e886600-2abd-11e9-968f-280dc0fe61b0.png)

Version 5 & 6
![image](https://user-images.githubusercontent.com/5565891/52423481-d4ddc500-2abd-11e9-972a-2b3d1ae714cd.png)

The key is now to be specified on the component.  I don't know if that has anything to do with it, but as per [this article](https://stackoverflow.com/questions/40014160/recaptcha-placeholder-element-must-be-an-element-or-id) the error was caused by the script being added multiple times...

**Comment by Enngage** [comment]
This kind of seems like some `racing` condition which is why it sometimes passes and sometimes not. The problem with global variables and google's script is that it can only be included once and when its initialized in the `load` callback (called when script is downloaded from CDN) it tries to setup the component. However, if the test already finishes and didn't wait (because how could Angular know it is supposed to wait?) it will remove components from DOM and thus google cannot find the component in question. 

One, quite naive, thing to do might be to wait certain amount of time (say you have a timeout for 5 secs) before quiting / executing the test so that everything has a change to initialize. Also, since the captcha is an external event, you might also need to use angular's `detectChanges` function. 

I know this is rather vague, but it kind of makes sense so maybe it will point you to the right direction.

**Comment by rts-cwalker** [comment]
@Enngage hmm. looks like that may have done the trick. I put this at the end of my `beforeEach()` in my tests that included the recaptcha and my unit tests have been passing since. 👍 

```
beforeEach(() => {
        fixture = TestBed.createComponent(ContactFormComponent);
        component = fixture.componentInstance;
        setTimeout(function () {
            fixture.detectChanges();
        }, 2000);
});
```

**Comment by JakeLardinois** [comment]
Ok. Makes sense.  Thanks!
Any idea why version ^4.7.0 doesn't have this issue?
BTW - Thanks for the plugin!

**Comment by rts-cwalker** [comment]
@Enngage I think we can close this issue as your suggestion helped fix the issue unless anyones else has a good reason not to. 👍

**Comment by Enngage** [comment]
Awesome, I'll include this information in readme as well because there have been quite a few issues with this. Thank you for the confirmation :)

**Comment by JakeLardinois** [comment]
The above did not work for me; most likely because I use an async beforeEach.  So what I did was to make the test asynchronous and then postpone it's execution with a timeout function.
![image](https://user-images.githubusercontent.com/5565891/52598555-b78d5b80-2e1b-11e9-9f33-cc512c0958f9.png)

**Comment by rts-cwalker** [comment]
I do want to point out, that it seems if you dont put a long enough timeout, it seems that it throws an error regarding calling `detectChanges()` out of scope or something (Im going off of memory as i write this since im not at my computer). So it seems that the more tests you are running, the longer the timeout probably needs to be would be my guess. :/ kind of a hack work around, but seems to do the trick at least

**Comment by JakeLardinois** [comment]
Yeah, the error I got when using the setTimeout inside my async beforeEach was "ViewDestroyedError: Attempt to use a destroyed view: detectChanges thrown"
![image](https://user-images.githubusercontent.com/5565891/52599583-a98d0a00-2e1e-11e9-8b87-12a3a3a38559.png)

**Comment by marcel-ploch** [comment]
Hey Everyone,

best way for me to do this is Mock the Ngx-Captcha Component during Unit Test Time.
`@Component({
  selector: 'ngx-recaptcha2',
  template: '<input type="text" [value]="" />',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NgxCaptchaMock),
      multi: true,
    },
  ],
})
class NgxCaptchaMock implements ControlValueAccessor {
  @Input() siteKey;
  @Input() formControlName;
  writeValue(obj: any): void {}
  registerOnChange(fn: any): void {}
  registerOnTouched(fn: any): void {}
  setDisabledState?(isDisabled: boolean): void {}
}`

Maybe it is Possible to obtain a separate TestingComponent inside the Library which could be provided for testing.
BeforeEach Needs than the No_Error_Schema
`
 beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [CaptchaComponent, NgxCaptchaMock],
      imports: [ReactiveFormsModule, RouterTestingModule, HttpClientTestingModule],
      schemas: [NO_ERRORS_SCHEMA],
    }).compileComponents();
  }));
`

**Comment by kxying-kk** [comment]
@marcel-ploch can you please post how to Mock the Ngx-Captcha Component during Unit Test Time? when i created this mock component. it asks to add it in app.module. after i added it in app.module, it says selector: 'ngx-recaptcha2' is duplicate. 

did you need to add this mock component in app.module? 

thanks.
