### ISSUE TITLE
Dark theme for Invisible reCaptcha

### ISSUE THREAD

**Issue by oxaoo** [Enngage/ngx-captcha#42]
I would like to have a dark theme for the invisible reCaptcha. Is it possible to do in the nearest release?
Thank you in advance!

**Comment by Enngage** [comment]
I don't believe google supports `dark` theme for invisible reCaptcha and no theming is listed on their official docs - https://developers.google.com/recaptcha/docs/invisible 

If you think there is a way to do this, feel free to let me know and reopen the issue.

**Comment by Enngage** [comment]
Turns out I wasn't right - you can use theming for invisible captcha as well. It just wasn't really that clear from the docs. I've released it under `6.3.0` and updates on-line docs accordingly.
