### ISSUE TITLE
.reset() no longer working

### ISSUE THREAD

**Issue by Youngevgeni** [Enngage/ngx-captcha#45]
like title, recaptcha.resetCaptcha(); is no longer working.

using:
"@angular/core": "^6.x.x",
"ngx-captcha": "5.0.4",

**Comment by Enngage** [comment]
There was indeed a problem in some previous version where reset was not working, but its not the case anymore in latest versions (6.x.y). Please update to newer version, I won't be deploying fixes to older angular versions since v6 and v7 are both compatible in case of this library.

**Comment by Youngevgeni** [comment]
the documentation is written
```
Supported versions
For Angular 6 use ngx-captcha on version 5.0.4
For Angular 7 use ngx-captcha on version >= 6.0.0
```

or you can
For Angular 6 use ngx-captcha on version >= 6.0.0
?

**Comment by Enngage** [comment]
Yeah, feel free to use latest version. It will work ok. I will probably
remove that info from docs.

**Comment by Youngevgeni** [comment]
Sorry for the inconvenience. Thank you very much

**Comment by Enngage** [comment]
Np, hope it works well :-)
