### ISSUE TITLE
Fatal Error When Building Angular Application

### ISSUE THREAD

**Issue by TaylorChristie** [Enngage/ngx-captcha#5]
Im using angular 6.0.0, and the recaptcha displays fine when in development mode, however after building the application I get the following error in my browser console, and I cannot access the application:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'ReCaptcha2' of undefined
TypeError: Cannot read property 'ReCaptcha2' of undefined
    at new n (main.133800a16123fd74e29c.js:1)
    at wa (main.133800a16123fd74e29c.js:1)
    at ba (main.133800a16123fd74e29c.js:1)
    at eu (main.133800a16123fd74e29c.js:1)
    at du (main.133800a16123fd74e29c.js:1)
    at lu (main.133800a16123fd74e29c.js:1)
    at eu (main.133800a16123fd74e29c.js:1)
    at Ka (main.133800a16123fd74e29c.js:1)
    at Object.mu [as createRootView] (main.133800a16123fd74e29c.js:1)
    at n.create (main.133800a16123fd74e29c.js:1)
    at new n (main.133800a16123fd74e29c.js:1)
    at wa (main.133800a16123fd74e29c.js:1)
    at ba (main.133800a16123fd74e29c.js:1)
    at eu (main.133800a16123fd74e29c.js:1)
    at du (main.133800a16123fd74e29c.js:1)
    at lu (main.133800a16123fd74e29c.js:1)
    at eu (main.133800a16123fd74e29c.js:1)
    at Ka (main.133800a16123fd74e29c.js:1)
    at Object.mu [as createRootView] (main.133800a16123fd74e29c.js:1)
    at n.create (main.133800a16123fd74e29c.js:1)
    at j (polyfills.e47a7446871b5070479b.js:1)
    at j (polyfills.e47a7446871b5070479b.js:1)
    at polyfills.e47a7446871b5070479b.js:1
    at e.invokeTask (polyfills.e47a7446871b5070479b.js:1)
    at Object.onInvokeTask (main.133800a16123fd74e29c.js:1)
    at e.invokeTask (polyfills.e47a7446871b5070479b.js:1)
    at t.runTask (polyfills.e47a7446871b5070479b.js:1)
    at d (polyfills.e47a7446871b5070479b.js:1)
nn @ main.133800a16123fd74e29c.js:1
e.handleError @ main.133800a16123fd74e29c.js:1
next @ main.133800a16123fd74e29c.js:1
n.object.o @ main.133800a16123fd74e29c.js:1
n.__tryOrUnsub @ main.133800a16123fd74e29c.js:1
n.next @ main.133800a16123fd74e29c.js:1
n._next @ main.133800a16123fd74e29c.js:1
n.next @ main.133800a16123fd74e29c.js:1
n.next @ main.133800a16123fd74e29c.js:1
n.emit @ main.133800a16123fd74e29c.js:1
(anonymous) @ main.133800a16123fd74e29c.js:1
e.invoke @ polyfills.e47a7446871b5070479b.js:1
t.run @ polyfills.e47a7446871b5070479b.js:1
e.runOutsideAngular @ main.133800a16123fd74e29c.js:1
onHandleError @ main.133800a16123fd74e29c.js:1
e.handleError @ polyfills.e47a7446871b5070479b.js:1
t.runGuarded @ polyfills.e47a7446871b5070479b.js:1
e @ polyfills.e47a7446871b5070479b.js:1
n.microtaskDrainDone @ polyfills.e47a7446871b5070479b.js:1
d @ polyfills.e47a7446871b5070479b.js:1
Promise.then (async)
v @ polyfills.e47a7446871b5070479b.js:1
e.scheduleTask @ polyfills.e47a7446871b5070479b.js:1
onScheduleTask @ polyfills.e47a7446871b5070479b.js:1
e.scheduleTask @ polyfills.e47a7446871b5070479b.js:1
t.scheduleTask @ polyfills.e47a7446871b5070479b.js:1
t.scheduleMicroTask @ polyfills.e47a7446871b5070479b.js:1
z @ polyfills.e47a7446871b5070479b.js:1
e.then @ polyfills.e47a7446871b5070479b.js:1
e.appInitializer @ main.133800a16123fd74e29c.js:1
e.runInitializers @ main.133800a16123fd74e29c.js:1
(anonymous) @ main.133800a16123fd74e29c.js:1
(anonymous) @ main.133800a16123fd74e29c.js:1
e.invoke @ polyfills.e47a7446871b5070479b.js:1
onInvoke @ main.133800a16123fd74e29c.js:1
e.invoke @ polyfills.e47a7446871b5070479b.js:1
t.run @ polyfills.e47a7446871b5070479b.js:1
e.run @ main.133800a16123fd74e29c.js:1
e.bootstrapModuleFactory @ main.133800a16123fd74e29c.js:1
zUnb @ main.133800a16123fd74e29c.js:1
p @ runtime.6afe30102d8fe7337431.js:1
7 @ main.133800a16123fd74e29c.js:1
p @ runtime.6afe30102d8fe7337431.js:1
n @ runtime.6afe30102d8fe7337431.js:1
e @ runtime.6afe30102d8fe7337431.js:1
(anonymous) @ main.133800a16123fd74e29c.js:1
```

I've updated the package to 2.1.0. The strange thing is that it works fine not built, it only runs into issues when building.

**Comment by Enngage** [comment]
Hi, that compiled output doesn't really say much. Can you try turning of build optimizer for your angular production builds to see more information?

**Comment by TaylorChristie** [comment]
The build actually works just fine without aot, buildOptimizer and optimization. I've turned them all off and experimented. It seems that the build optimizer is causing the error (as I was able to have it run successfully without buildOptimizer on):
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'ReCaptcha2' of undefined
TypeError: Cannot read property 'ReCaptcha2' of undefined
    at new ReCaptcha2Component (main.b353ad2ea666cb98be56.js:57465)
    at createClass (main.b353ad2ea666cb98be56.js:18306)
    at createDirectiveInstance (main.b353ad2ea666cb98be56.js:18187)
    at createViewNodes (main.b353ad2ea666cb98be56.js:19406)
    at callViewAction (main.b353ad2ea666cb98be56.js:19722)
    at execComponentViewsAction (main.b353ad2ea666cb98be56.js:19641)
    at createViewNodes (main.b353ad2ea666cb98be56.js:19434)
    at createRootView (main.b353ad2ea666cb98be56.js:19320)
    at Object.createProdRootView [as createRootView] (main.b353ad2ea666cb98be56.js:19835)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (main.b353ad2ea666cb98be56.js:17662)
    at new ReCaptcha2Component (main.b353ad2ea666cb98be56.js:57465)
    at createClass (main.b353ad2ea666cb98be56.js:18306)
    at createDirectiveInstance (main.b353ad2ea666cb98be56.js:18187)
    at createViewNodes (main.b353ad2ea666cb98be56.js:19406)
    at callViewAction (main.b353ad2ea666cb98be56.js:19722)
    at execComponentViewsAction (main.b353ad2ea666cb98be56.js:19641)
    at createViewNodes (main.b353ad2ea666cb98be56.js:19434)
    at createRootView (main.b353ad2ea666cb98be56.js:19320)
    at Object.createProdRootView [as createRootView] (main.b353ad2ea666cb98be56.js:19835)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (main.b353ad2ea666cb98be56.js:17662)
    at resolvePromise (polyfills.ed33b00ebf44d2d246c1.js:3130)
    at resolvePromise (polyfills.ed33b00ebf44d2d246c1.js:3087)
    at polyfills.ed33b00ebf44d2d246c1.js:3189
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.ed33b00ebf44d2d246c1.js:2737)
    at Object.onInvokeTask (main.b353ad2ea666cb98be56.js:12276)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.ed33b00ebf44d2d246c1.js:2736)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (polyfills.ed33b00ebf44d2d246c1.js:2504)
    at drainMicroTaskQueue (polyfills.ed33b00ebf44d2d246c1.js:2911)
defaultErrorLogger @ main.b353ad2ea666cb98be56.js:9840
```

**Comment by Enngage** [comment]
I'm not so sure about that - we are using following production build and have no problems building & running it:

```
              "optimization": true,
              "sourceMap": false,
              "aot": true,
              "vendorChunk": false,
              "extractLicenses": true,
              "buildOptimizer": true
```

Are you able to reproduce this with generating new angular project using `ng new` to rule out influence of any custom code?

**Comment by Enngage** [comment]
FYI, I have myself reported some bugs regarding `buildOptimizer` as it may break 3rd party libraries (caused by uglify), but it doesn't seem to be relevant to your case as otherwise the build would have 'probably' failed for us too since we have buildOptimizer enabled.

**Comment by Bidthedog** [comment]
I'm getting this exact error (in Chrome developer console) when accessing an application after building with one of the following commands:

* ng serve --prod
* ng build --prod

AOT builds work fine, though:

* ng serve --aot
* ng build --aot

Attempted to clear cache, reinstall packages etc - still getting the issue in production mode.

**Comment by Bidthedog** [comment]
Just been fiddling with the angular cli settings. Setting `"buildOptimizer": false` sorts the issue - but that's not ideal. Latest version of everything - here's my `npm list --depth=0` output:

```
$ npm list --depth=0
+-- @angular-devkit/build-angular@0.6.0
+-- @angular/animations@6.0.3
+-- @angular/cli@6.0.7
+-- @angular/common@6.0.3
+-- @angular/compiler@6.0.3
+-- @angular/compiler-cli@6.0.3
+-- @angular/core@6.0.3
+-- @angular/forms@6.0.3
+-- @angular/http@6.0.3
+-- @angular/language-service@6.0.3
+-- @angular/platform-browser@6.0.3
+-- @angular/platform-browser-dynamic@6.0.3
+-- @angular/router@6.0.3
+-- @ng-bootstrap/ng-bootstrap@2.0.0
+-- @types/jasmine@2.8.7
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.108
+-- bootstrap@4.1.1
+-- chokidar-cli@1.2.0
+-- codelyzer@4.3.0
+-- core-js@2.5.6
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.3.1
+-- karma@2.0.2
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@1.4.2
+-- karma-jasmine@1.1.2
+-- karma-jasmine-html-reporter@0.2.2
+-- moment@2.22.2
+-- ngx-captcha@2.2.1
+-- popper.js@1.14.3
+-- protractor@5.1.2
+-- rxjs@6.2.0
+-- ts-node@4.1.0
+-- tslint@5.9.1
+-- typescript@2.7.2
`-- zone.js@0.8.26

npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.9.1
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0
```

**Comment by Enngage** [comment]
Hi, 

I would like to investigate this, but I'm unable to reproduce it locally. I've added production build to demo app and it works ok (see [angular.json](https://github.com/Enngage/ngx-captcha/blob/master/angular.json#L46)) 

Any chance you can fork this repo and running it with `ng serve --prod` and possibly reproducing the issue here?

**Comment by Enngage** [comment]
Even though I can't seem to reproduce it on my demo app, I changed build to use ng-packgr which could help with this issue.

**Comment by gitneeraj** [comment]
Hey,

I get this error while doing `ng build --prod`

`ERROR in src/app/components/landing/contact/contact.component.html(51,92): : Property 'recaptcha' does not exist on type 'ContactComponent'.`

**package.json**
`{
  "name": "bkpack",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build-prod": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev": "ng build --watch"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "^0.10.6",
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/pwa": "^0.11.4",
    "@angular/router": "~7.0.0",
    "@angular/service-worker": "~7.0.0",
    "@fortawesome/fontawesome-free": "^5.5.0",
    "@glidejs/glide": "^3.2.6",
    "angulartics2": "^7.3.0",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "eslint": "^5.10.0",
    "inquirer": "^6.2.0",
    "jquery": "^3.3.1",
    "ngx-captcha": "^6.3.0",
    "ngx-google-places-autocomplete": "^2.0.1",
    "ngx-slick-carousel": "^0.4.4",
    "ngx-toastr": "^9.1.1",
    "popper.js": "^1.14.3",
    "rxjs": "~6.3.3",
    "scrollmagic": "^2.0.6",
    "slick-carousel": "^1.8.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.10.6",
    "@angular/cli": "~7.0.4",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}
`

**angular.json**
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "angular-base": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.json"
            ],
            "styles": [
              "node_modules/@fortawesome/fontawesome-free/css/all.css",
              "src/assets/scss/base.scss",
              "node_modules/ngx-toastr/toastr.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js",
              "node_modules/scrollmagic/scrollmagic/minified/ScrollMagic.min.js"
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ],
              "serviceWorker": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "angular-base:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "angular-base:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "angular-base:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.json"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "angular-base-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "prefix": "",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "angular-base:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "angular-base:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "angular-base"
}`

It works fine on `ng serve`

Any help much appreciated!

-Neeraj
