### ISSUE TITLE
[QUESTION] Really need reCaptcha, can I use ngx-formly

### ISSUE THREAD

**Issue by moplin** [Enngage/ngx-captcha#50]
So the question, I am using ngx-formly, can I integrate it with ngx-recaptcha, or what would be the best way to use recaptcha in this scenario? Please some help.

**Comment by Enngage** [comment]
I have no affiliation and have never used `ngx-formly` so sadly I can't really help you with this. You can use `ngx-captcha` both standalone or as a part of Angular's form engine, but thats all I can say.
