### ISSUE TITLE
Throws error while using ng build --prod

### ISSUE THREAD

**Issue by gitneeraj** [Enngage/ngx-captcha#51]
Hey,

I get this error while doing ng build --prod

ERROR in src/app/components/landing/contact/contact.component.html(51,92): : Property 'recaptcha' does not exist on type 'ContactComponent'.

package.json
{ "name": "bkpack", "version": "0.0.0", "scripts": { "ng": "ng", "start": "ng serve", "build": "ng build", "build-prod": "ng build --prod", "test": "ng test", "lint": "ng lint", "e2e": "ng e2e", "dev": "ng build --watch" }, "private": true, "dependencies": { "@angular-devkit/build-angular": "^0.10.6", "@angular/animations": "~7.0.0", "@angular/common": "~7.0.0", "@angular/compiler": "~7.0.0", "@angular/core": "~7.0.0", "@angular/forms": "~7.0.0", "@angular/http": "~7.0.0", "@angular/platform-browser": "~7.0.0", "@angular/platform-browser-dynamic": "~7.0.0", "@angular/pwa": "^0.11.4", "@angular/router": "~7.0.0", "@angular/service-worker": "~7.0.0", "@fortawesome/fontawesome-free": "^5.5.0", "@glidejs/glide": "^3.2.6", "angulartics2": "^7.3.0", "bootstrap": "^4.1.3", "core-js": "^2.5.4", "eslint": "^5.10.0", "inquirer": "^6.2.0", "jquery": "^3.3.1", "ngx-captcha": "^6.3.0", "ngx-google-places-autocomplete": "^2.0.1", "ngx-slick-carousel": "^0.4.4", "ngx-toastr": "^9.1.1", "popper.js": "^1.14.3", "rxjs": "~6.3.3", "scrollmagic": "^2.0.6", "slick-carousel": "^1.8.1", "zone.js": "~0.8.26" }, "devDependencies": { "@angular-devkit/build-angular": "^0.10.6", "@angular/cli": "~7.0.4", "@angular/compiler-cli": "~7.0.0", "@angular/language-service": "~7.0.0", "@types/jasmine": "~2.8.8", "@types/jasminewd2": "~2.0.3", "@types/node": "~8.9.4", "codelyzer": "~4.5.0", "jasmine-core": "~2.99.1", "jasmine-spec-reporter": "~4.2.1", "karma": "~3.0.0", "karma-chrome-launcher": "~2.2.0", "karma-coverage-istanbul-reporter": "~2.0.1", "karma-jasmine": "~1.1.2", "karma-jasmine-html-reporter": "^0.2.2", "protractor": "~5.4.0", "ts-node": "~7.0.0", "tslint": "~5.11.0", "typescript": "~3.1.1" } }

angular.json
{ "$schema": "./node_modules/@angular/cli/lib/config/schema.json", "version": 1, "newProjectRoot": "projects", "projects": { "angular-base": { "root": "", "sourceRoot": "src", "projectType": "application", "prefix": "app", "schematics": { "@schematics/angular:component": { "styleext": "scss" } }, "architect": { "build": { "builder": "@angular-devkit/build-angular:browser", "options": { "outputPath": "dist", "index": "src/index.html", "main": "src/main.ts", "polyfills": "src/polyfills.ts", "tsConfig": "src/tsconfig.app.json", "assets": [ "src/favicon.ico", "src/assets", "src/manifest.json" ], "styles": [ "node_modules/@fortawesome/fontawesome-free/css/all.css", "src/assets/scss/base.scss", "node_modules/ngx-toastr/toastr.css" ], "scripts": [ "node_modules/jquery/dist/jquery.min.js", "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js", "node_modules/scrollmagic/scrollmagic/minified/ScrollMagic.min.js" ] }, "configurations": { "production": { "fileReplacements": [ { "replace": "src/environments/environment.ts", "with": "src/environments/environment.prod.ts" } ], "optimization": true, "outputHashing": "all", "sourceMap": false, "extractCss": true, "namedChunks": false, "aot": true, "extractLicenses": true, "vendorChunk": false, "buildOptimizer": true, "budgets": [ { "type": "initial", "maximumWarning": "2mb", "maximumError": "5mb" } ], "serviceWorker": true } } }, "serve": { "builder": "@angular-devkit/build-angular:dev-server", "options": { "browserTarget": "angular-base:build" }, "configurations": { "production": { "browserTarget": "angular-base:build:production" } } }, "extract-i18n": { "builder": "@angular-devkit/build-angular:extract-i18n", "options": { "browserTarget": "angular-base:build" } }, "test": { "builder": "@angular-devkit/build-angular:karma", "options": { "main": "src/test.ts", "polyfills": "src/polyfills.ts", "tsConfig": "src/tsconfig.spec.json", "karmaConfig": "src/karma.conf.js", "styles": [], "scripts": [], "assets": [ "src/favicon.ico", "src/assets", "src/manifest.json" ] } }, "lint": { "builder": "@angular-devkit/build-angular:tslint", "options": { "tsConfig": [ "src/tsconfig.app.json", "src/tsconfig.spec.json" ], "exclude": [ "**/node_modules/**" ] } } } }, "angular-base-e2e": { "root": "e2e/", "projectType": "application", "prefix": "", "architect": { "e2e": { "builder": "@angular-devkit/build-angular:protractor", "options": { "protractorConfig": "e2e/protractor.conf.js", "devServerTarget": "angular-base:serve" }, "configurations": { "production": { "devServerTarget": "angular-base:serve:production" } } }, "lint": { "builder": "@angular-devkit/build-angular:tslint", "options": { "tsConfig": "e2e/tsconfig.e2e.json", "exclude": [ "**/node_modules/**" ] } } } } }, "defaultProject": "angular-base" }

It works fine on ng serve

Any help much appreciated!

-Neeraj

**Comment by gitneeraj** [comment]
With these settings in angular.json, works fine. But I guess its highly not recommended to turn off optimizations as the file sizes go high(my main.js went upto 5MB).

```
"optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false,
```

**Comment by Enngage** [comment]
Hi, this is not a problem with this library, but with your `contact.component.html` and the fact it contains reference to `recaptcha` from within  `ContactComponent` which does not exist. 

It works during `ng serve` because it has less strict rules (if you are using default configuration which you likely are).
