### ISSUE TITLE
reCaptcha v2 using ngx-captcha not visible in IE11,but working fine in chrome

### ISSUE THREAD

**Issue by Bombay2018** [Enngage/ngx-captcha#52]
Standard code has been used to implement captcha in my login page from https://www.npmjs.com/package/ngx-captcha,and working finechrome
but captcha is not visible in IE11.

**Comment by Enngage** [comment]
https://enngage.github.io/ngx-captcha/ is working fine in IE11. Did you add Angular polyfills to IE?
