### ISSUE TITLE
Execute() only have 1 argument

### ISSUE THREAD

**Issue by GuysmoB** [Enngage/ngx-captcha#55]
Hi,

I try to use the V3 but the execute() method have only 1 parameter in his definition so I can't use :
`this.reCaptchaV3Service.execute(this.siteKey, 'homepage', (token) => {
   console.log('This is your token: ', token);
 }, {
     useGlobalDomain: false
 });`

Any idea ?

Thanks

**Comment by Enngage** [comment]
I don't understand.. The execute method has 3 parameters as can be seen at - https://github.com/Enngage/ngx-captcha/blob/master/projects/ngx-captcha-lib/src/lib/services/recaptcha_v3.service.ts#L23

**Comment by GuysmoB** [comment]
The problem was a conflict between multiple captcha dependencies.
