### ISSUE TITLE
Global config

### ISSUE THREAD

**Issue by ChaudhryAtif** [Enngage/ngx-captcha#56]
> Import NgxCaptchaModule to your module (i.e. AppModule). You can configure global keys with forRoot (optionally) or you can use siteKey input parameter of captcha components.

I tried searching for an example, but could not find one.

When checking `ngx-captcha.module.d.ts`, it does not have a forRoot function.

How can I globally configure siteKey, and other properties (i.e. size, theme, type, etc.)?

Edit: I searched for global, but not 'forRoot'. Found this: https://github.com/Enngage/ngx-captcha/issues/24

So siteKey cannot be configured globally? Can other properties still be configured? If not, docs mayneed to be updated.

**Comment by Enngage** [comment]
Hey, this was an old configuration option. Currently you can pass `siteKey `to component directly. Where in docs is this mentioned?
