### ISSUE TITLE
update deps to angular 8

### ISSUE THREAD

**Issue by fxck** [Enngage/ngx-captcha#57]
8 is out now https://github.com/angular/angular/blob/master/CHANGELOG.md#800-2019-05-28

```
npm WARN ngx-captcha@6.4.0 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-captcha@6.4.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by vdumbrav** [comment]
@Enngage 

Angular 8 and enableIvy: true

```
ERROR in src/__ng_typecheck__.ts(252,11): error TS2339: Property 'siteKey' does not exist on type 'HTMLElement'.
src/__ng_typecheck__.ts(253,11): error TS2339: Property 'type' does not exist on type 'HTMLElement'.
src/__ng_typecheck__.ts(254,11): error TS2339: Property 'useGlobalDomain' does not exist on type 'HTMLElement'.
```

**Comment by Enngage** [comment]
@vdumbrav, so these properties exist in base class (e.g. https://github.com/Enngage/ngx-captcha/blob/master/projects/ngx-captcha-lib/src/lib/components/base-recaptcha.component.ts#L37 ) and I guess this is up to Angular team to fix as it should be backwards compatible and being able to process base class seems like a reasonable thing to support. 

I could probably try moving those properties, but I would rather wait until ivy is more production ready.

**Comment by Enngage** [comment]
I'm closing this one though as Angular 8 is generally supported, while ivy is not.
