### ISSUE TITLE
div staying in my DOM

### ISSUE THREAD

**Issue by UlisesCeca** [Enngage/ngx-captcha#58]
Hello, when I open a register modal in my App and then the recaptcha 2 is loaded, this div is created in my DOM:

`<div style="visibility: visible; position: absolute; width: 320px; top: 17.5312px; left: 0px; right: 0px; transition: visibility 0s linear 0s, opacity 0.3s linear 0s; opacity: 1;"><div style="width: 100%; height: 100%; position: fixed; top: 0px; left: 0px; z-index: 2000000000; background-color: rgb(255, 255, 255); opacity: 0.5;"></div><div style="margin: 0px auto; top: 0px; left: 0px; right: 0px; position: absolute; border: 1px solid rgb(204, 204, 204); z-index: 2000000000; background-color: rgb(255, 255, 255); overflow: hidden; width: 300px; height: 510px;"><iframe title="Reto recaptcha" src="https://www.google.com/recaptcha/api2/bframe?hl=es&amp;v=v1559543665173&amp;k=6LfYMacUAAAAAE2SK7RrWnYu9kgTCkzJUCfyqY84&amp;cb=kmcjzjo8dv4j" name="c-s0i32k6d40f5" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox" style="width: 300px; height: 510px;"></iframe></div></div>`

Then if I close my component it won't dissapear and if I open it again, I'll have two.

How can I fix this? Thanks.

**Comment by FerAnimaciones** [comment]
Same issue.
![image](https://user-images.githubusercontent.com/20001641/69823329-ca63f780-11c5-11ea-87ab-1e896d9265c2.png)

**Comment by FerAnimaciones** [comment]
I made this. 
![image](https://user-images.githubusercontent.com/20001641/69824950-bc64a580-11ca-11ea-964e-b00652caa3e4.png)
```
  ngOnDestroy() {
    var list = document.getElementsByClassName("body-class");
    var last=list[0].lastChild;
    if(last['style']['background-color']){
        list[0].removeChild(last);
    }
  }
```
![GIF 28-11-2019 10-37-22 a  m](https://user-images.githubusercontent.com/20001641/69825079-4876cd00-11cb-11ea-89ac-0543f27916f6.gif)

**Comment by evheniyrz** [comment]
It's resolved for me. -> Angular 8, ngx-captcha 7.0.0

`
@ViewChildren('recaptcha') invisibleRecaptchaList: QueryList<InvisibleReCaptchaComponent>;
ngOnDestroy(): void {this.invisibleRecaptchaList.first.resetCaptcha() }`

It delete a  div element from body.
