### ISSUE TITLE
Bug with testing recaptcha

### ISSUE THREAD

**Issue by cTahirih** [Enngage/ngx-captcha#62]
I need help with this error when execute testing
TypeError: this.reCaptchaApi.render is not a function

I followed this as a guide, because I have the same problem, but it didn't help me fix it
https://stackoverflow.com/questions/54146810/angular-test-case-returns-typeerror-this-recaptchaapi-render-is-not-a-function

I read your possible solution using setTimeOut, but this generate more bugs in test

**Comment by YogiParekh** [comment]
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

 beforeEach(async () => {
    fixture = TestBed.createComponent(RegisterComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
    await sleep(500);
  });
