### ISSUE TITLE
google chrome warnings

### ISSUE THREAD

**Issue by hssamconf** [Enngage/ngx-captcha#68]
After a successful integration of ngx-captcha and while testing on localhost i got this several warnings :

Chrome Version 79.0.3945.88 (Official build) (64 bits)

> A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

An idea on how can I hide them ?

**Comment by Enngage** [comment]
I'm not storing any cookies within this library, but paypal is. If this is a problem, paypal will issue a  fix for this. There is nothing I could do.

**Comment by fromage9747** [comment]
@Enngage PayPal is linked to this library?  I understand that there shouldn't be anything to worry about, but how can this be handled so that this is not displayed in the console log when using your module?

**Comment by Enngage** [comment]
I can't influence this, PayPal needs to update their lib (or publish new one) with the fix for new chrome versions.

**Comment by fromage9747** [comment]
@Enngage thanks for the clarification
