### ISSUE TITLE
reCAPTCHA has already been rendered in this element.

### ISSUE THREAD

**Issue by Patira** [Enngage/ngx-captcha#7]
I'm using two components (signup and login) with ngx-captcha in each of these components.

Now when I'm trying to navigate between these two components (from signup to login), I get this "reCAPTCHA has already been rendered in this element" error.

I tried everything I could in ngOnDestroy in order to reset and reload the captcha in each of the components. Still getting the same error.

Other than that, everything is working just fine. Wondering if I'm doing something wrong?

**Comment by Enngage** [comment]
I've made some changes to the code, can you try updating to `2.2.0`? Let me know how that works.

**Comment by Enngage** [comment]
There was a minor bug with captcha id, try using `2.2.1`

**Comment by Patira** [comment]
You're awesome man!
The error is gone now. But sure, there is another one! :)
reCAPTCHA couldn't find user-provided function: ngx_onload_callback_**SOME_RANDOM_NUMBER**

**Comment by Patira** [comment]
Look here:
https://github.com/Patira/ngx-captcha/commit/a2bcfd6bfa67195d3b816f8a78c3a837a768c974

I just added a navigation that tries to mock authentication and redirects a user to another page.

Now, try to go to invisible recaptcha page with your console open and you will see the error that I'm talking about.

**Comment by Enngage** [comment]
Thanks for that! Ah, I see what you mean. Though I'm not sure this is something I can fix on my end. The console log you see is coming from google script which says that the callback method could not be found. The thing is that Angular's `ngOnChanges` is called before `ngOnInit` and so if you include captcha elem on page it will register the google script along with the callback and if you redirect before the google script has a change to initialize, the component will already be destroyed. 

Is this causing you any issues? If not, I would leave it as it is. If it is, then maybe consider using *ngIf along with some condition on the `ngx-captcha` components so they are not registered until they are really needed.

**Comment by Patira** [comment]
It's not causing any issues. I just wanted to know if it is indeed, an issue and whether I'm doing something wrong :/ Thanks for your great explanation and your excellent efforts for this project in here :)

**Comment by Enngage** [comment]
Okey, thank you :-) Glad it works.

**Comment by biswajit358** [comment]
I am facing the above issue in 
    "ngx-captcha": "^6.2.0", Can you suggest how can i fix it.
