### ISSUE TITLE
Need to update for Angular 9

### ISSUE THREAD

**Issue by dmytrodemchenko** [Enngage/ngx-captcha#70]

**Comment by Enngage** [comment]
I will update soon

**Comment by dmytrodemchenko** [comment]
@Enngage could you please provide with potential date of release update with support Angular 9?

**Comment by dmytrodemchenko** [comment]
@Enngage I can help with update?

**Comment by Enngage** [comment]
Hi, its been released 2 days ago. I forgot about the issue, closing now.

**Comment by dmytrodemchenko** [comment]
@Enngage why it's v0.0.1?

**Comment by Enngage** [comment]
It's not -
https://github.com/Enngage/ngx-captcha/blob/master/projects/ngx-captcha-lib/package.json
