### ISSUE TITLE
Versions question

### ISSUE THREAD

**Issue by Exocomp** [Enngage/ngx-captcha#74]
NPM lists the latest version as 8.0.1, this project release is on version 6.4.0, can you explain where there is a version difference?

**Comment by Enngage** [comment]
This is probably when I switched to ngpackagr and forgot to update releases.

**Comment by mlc-mlapis** [comment]
@Enngage What changes are related to version 9.0.1 from the 8.0.1 point of view?

**Comment by Enngage** [comment]
Sorry, I can't keep up with all projects  I have so you would have to look at commits yourself
