### ISSUE TITLE
CORS issue for Ionic iOS

### ISSUE THREAD

**Issue by dodomui** [Enngage/ngx-captcha#77]
For ionic iOS webview the host will be ionic://
Therefore it having CORS issue for recaptcha.

Also unable to set ionic:// as allow domain.
Any suggestion what could I do?

THanks.

**Comment by RohitG157** [comment]
@dodomui 
In order to reCaptcha work in IOS with the WebView, you need to add the following to the config.xml: <allow-navigation href="https://www.recaptcha.net/*" />

Don't forget to add 'localhost' domain in the reCaptcha console.

**Comment by rpinto18** [comment]
@RohitG157 @dodomui 
any solution? Example please.

**Comment by RohitG157** [comment]
> @RohitG157 @dodomui
> any solution? Example please.

@rpinto18 You can add the following line in the config.xml:

`<allow-navigation href="https://www.recaptcha.net/*" />`
