### ISSUE TITLE
Cannot bind

### ISSUE THREAD

**Issue by gridcellcoder** [Enngage/ngx-captcha#8]
Hi 

We've followed the instructions on github and added ` "ngx-captcha": "^2.2.0"`

```
NgxCaptchaModule.forRoot({
      reCaptcha2SiteKey: 'xxx', // optional, can be overridden with 'siteKey' component property
      invisibleCaptchaSiteKey: 'yyy' // optional, can be overridden with 'siteKey' component property
    })
```

using valid keys (tested in another project)

to `@NgModule({
  imports: [`

but we're getting:

```
Uncaught Error: Template parse errors:
Can't bind to 'size' since it isn't a known property of 'ngx-recaptcha2'.
1. If 'ngx-recaptcha2' is an Angular component and it has 'size' input, then verify that it is part of this module.
2. If 'ngx-recaptcha2' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </a></mat-card-actions>
          <ngx-recaptcha2
            [ERROR ->][size]="size"
            [hl]="lang"
            [theme]="theme"
```

here is our package.json

```
"dependencies": {
    "@angular/animations": "6.0.0",
    "@angular/cdk": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "6.0.0",
    "@angular/http": "6.0.0",
    "@angular/material": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/router": "6.0.0",
    "angularfire2": "5.0.0-rc.10",
    "@ngrx/effects": "^6.0.0-beta.1",
    "@ngrx/store": "^6.0.0-beta.1",
    "binaryjs-client": "1.0.0",
    "bootstrap": "^4.0.0",
    "browser-detect": "^0.2.27",
    "core-js": "^2.4.1",
    "firebase": "5.0.4",
    "font-awesome": "^4.7.0",
    "ngx-captcha": "^2.2.0",
    "rxjs": "^6.0.0",
    "uuid": "^3.1.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.20"
  },
```

please can you help us figure out why this is not binding/compiling?

**Comment by Enngage** [comment]
Hi, this likely means that the ngx-recaptcha2 component is not included in the module of the component in which you are trying to use it. To which module have you imported the NgxCaptchaModule module?

**Comment by Enngage** [comment]
Closing as unrelevant to this package

**Comment by acegilz** [comment]
Having the same issue.

> this likely means that the ngx-recaptcha2 component is not included in the module of the component in which you are trying to use it

Can you please clarify? There is nothing on the document that tells to import ngx-recaptcha2 components

**Comment by Enngage** [comment]
This has to do with Angular modules (see [docs](https://angular.io/guide/architecture-modules)). In a nutshell this means that your `LoginComponent` is declared in some module and that module needs to import the `NgxCaptchaModule`. However, I think that including in AppModule should be sufficient, but I can't really say how you are using that specifically. 

If you are unsure, please download the demo app and play with that: https://github.com/Enngage/ngx-captcha/tree/master/demo
