### ISSUE TITLE
Angular 10 Peer Dependencies

### ISSUE THREAD

**Issue by clark-stevenson** [Enngage/ngx-captcha#83]
Hey @Enngage  Awesome library! Thanks for sharing it. 

Today I was updating to Angular 10, and on doing so I recieve the following warnings:

```
npm WARN ngx-captcha@8.0.1 requires a peer of @angular/common@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-captcha@8.0.1 requires a peer of @angular/core@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-captcha@8.0.1 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
```

Would it be possible to take a look at updating these dependencies?

**Comment by andrejm7** [comment]
npm WARN ngx-captcha@8.0.1 requires a peer of @angular/common@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-captcha@8.0.1 requires a peer of @angular/core@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-captcha@8.0.1 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.


please..

**Comment by ravetroll** [comment]
I have been using this on my app singe Angular 6, so have just migrated it all the way to Angular 10.  This is the only component I am having trouble with this message,  Please update for Angular 10.

**Comment by atilamsantos** [comment]
No news about the upgrade? 
This library is awesome and will be great to upgrade to angular 10.

Pls give to us some feedback.

**Comment by inexuscore** [comment]
Is this repo actively maintained? I need to upgrade to Angular 11 and this is a blocking issue. Any plans to upgrade soon?

**Comment by Enngage** [comment]
Hey,

It's backwards compatible, so nothing should be stopping you from using it
in Angular 11. Or maybe you have  some Ivy specific issue?

**Comment by inexuscore** [comment]
@Enngage Hiya,
No Ivy issues, just a warning about optimization bailouts coming from another package. I tried, couldn't upgrade to Angular 11 because of peer dependencies. I'll see if I can sort it out, thank you.

**Comment by ravetroll** [comment]
I was getting the peer dependencies error when I upgraded from angular 9 to 10, meaning I couldn't compile.  I then cleared out my npm cache, reinstalled everything, and for some reason it gave no errors and started compiling.  Before that it was referring to the Angular 9.0.0 in peer dependencies being the problem, which made sense since I was using Angular 10.0.0.

**Comment by Zwartpet** [comment]
https://github.com/Enngage/ngx-captcha/pull/90 created pull request for Angular 11 update

**Comment by Enngage** [comment]
New version released ;)

**Comment by clark-stevenson** [comment]
Thank you @Zwartpet and @Enngage for finding time to do this! 💘
