### ISSUE TITLE
Captcha element with id 'ngx_captcha_id_XXXX' was not found

### ISSUE THREAD

**Issue by shreyshahh** [Enngage/ngx-captcha#87]
Hi I am using ngx-captcha2 and [Ngx-admin](https://www.akveo.com/ngx-admin/pages/dashboard?utm_campaign=ngx_admin%20-%20demo%20-%20ngx_admin%20docs&utm_source=ngx_admin&utm_medium=referral&utm_content=landing_main_section). This error comse when I use captcha inside Nebular tabset, otherwise it is working fine. Any solution for this or any workarounds?

```
<nb-card>
    <nb-card-header></nb-card-header>
    <nb-card-body>
        <nb-tabset>
            <nb-tab>
                // code for reCaptcha
            </nb-tab>
        </nb-tabset>
    </nb-card-body>
</nb-card>
```

**Comment by jitendraP-ashutec** [comment]
@shreyshahh  I have also faced this issue with angular cdk stepper. I have created PR https://github.com/Enngage/ngx-captcha/pull/91 to resolve this issue. If @Enngage will merge this solution then you can download from npm. but for now you can download it here: https://github.com/jitendraP-ashutec/ngx-captcha-package/blob/main/ngx-captcha-9.0.0.tgz
and add this file in root folder and add below line in package.json and run `npm install` so package will be install locally.

```
...
  "dependencies": {
...
     "ngx-captcha": "file:ngx-captcha-9.0.0.tgz",
...

```

**Comment by Enngage** [comment]
I merged & released updated version
