### ISSUE TITLE
How to provide nounce to solve the Security Policy issue

### ISSUE THREAD

**Issue by manuchadha1979** [Enngage/ngx-captcha#88]
I am trying to use `5.0.4` version and on first attempt, I got error `vendor.js:184374 Refused to load the script 'https://www.google.com/recaptcha/api.js?onload=ngx_captcha_onload_callback&render=explicit&hl=en' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

Reading here,  I could either add `script-src https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ ` or the preferred option is to use NOUNCE - https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website.-how-can-i-configure-it-to-work-with-recaptcha.

I can't find out the option to specify NOUNCE. How can I use Nounce?

**Comment by Enngage** [comment]
Sorry man, I have no idea what this is. Its working okay in the demo here https://enngage.github.io/ngx-captcha/ so its probably an issue on your end.

**Comment by PargatVineforce** [comment]
Can we add nonce in **ngx-captcha** for internal libraries https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ ?
