### ISSUE TITLE
Prod build uses invisibleCaptchaSiteKey for ngx-recaptcha2 when specified on NgxCaptchaModule

### ISSUE THREAD

**Issue by JakeLardinois** [Enngage/ngx-captcha#9]
When using the prod build ("ng serve --prod") the plugin uses the invisibleCaptchaSiteKey value for the recaptcha response (.getResponse()) even though I'm using the ngx-recaptcha2 directive.  This does not happen when running without --prod.  
   I first observed this when I deployed my app.  I received a "SiteKey for invisible reCaptcha is not set!" error, so I added the invisibleCaptchaSiteKey to the module declaration.  However, after doing that, the server side validation would fail until I used my Invisible Captcha secret for the server side validation.
  I did find that I am able to resolve the problem by setting the site key on the component property and so am using that as a temporary workaround.  Attached is my package.json
![image](https://user-images.githubusercontent.com/5565891/41409697-ae0b259e-6f9c-11e8-8a00-3e5a2ec0818b.png)

**Comment by Enngage** [comment]
That is definitely odd. I'm using shared abstract class in both components, but I'm puzzled as to why it would have this effect in production mode only. I'll try reproducing this, thanks!

**Comment by Enngage** [comment]
I can't seem to reproduce this, but I made some changes to code while moving to ng-packgr. Can you try with latest realease `3.0.0`?

**Comment by JakeLardinois** [comment]
Yep.  I will do and let you know the results asap.  Thanks for looking into this

**Comment by JakeLardinois** [comment]
So I verified the issue.  I removed this from my component
![image](https://user-images.githubusercontent.com/5565891/41670904-34c4e0b0-747b-11e8-981e-3db7451bc4ee.png)

added this back to my module
![image](https://user-images.githubusercontent.com/5565891/41670932-49f2a1c0-747b-11e8-9e32-e1fe2fe0bd6a.png)

When I use "ng serve --prod" I recieve the following error from the page
![image](https://user-images.githubusercontent.com/5565891/41670979-6ca1e5e6-747b-11e8-9700-980a10243265.png)

From there if I add the Invisible Recaptcha site key, then it will use that key for the server side recaptcha verification (note that client side will still validate)
Now I'll update to version 3 and see if the issue is resolved there.

**Comment by JakeLardinois** [comment]
Perfect!  Upgrading from version 2.2.1 to version 3.0.0 resolved it!  Thank you very much for your work on this

**Comment by Enngage** [comment]
Awesome, glad it helps! Thanks for the info.
