### ISSUE TITLE
Angular 11 Incompatibility

### ISSUE THREAD

**Issue by TomMettam** [Enngage/ngx-captcha#98]
While everything appears to work, the component throw this error with Angular 11:

```
ERROR NullInjectorError: R3InjectorError(WebModule)[NgControl -> NgControl -> NgControl]: 
  NullInjectorError: No provider for NgControl!
```

Thrown by: `InvisibleReCaptchaComponent.ngAfterViewInit`

**Comment by Enngage** [comment]
Reinstall your node_modules. This library is working with Angular 11 just fine as you can see in demo app - https://github.com/Enngage/ngx-captcha/tree/master/demo

**Comment by TomMettam** [comment]
The same error occurs in your demo, but ok.

(Note: it works fine, but the error appears in the browser console).

**Comment by Enngage** [comment]
I dont see the error in https://enngage.github.io/ngx-captcha/

**Comment by TomMettam** [comment]
Hm, no, i don't see it either on that page, but when I built the demo with the latest version of angular/cli and the latest angular release I did see it. Let me experiment and get back to you.

**Comment by Enngage** [comment]
I think there is some problem in your setup - manually deleting node_modules often solves similar issue, but hard to say ;)
