### ISSUE TITLE
Google recaptcha images not showing

### ISSUE THREAD

**Issue by swagata1603** [Enngage/ngx-captcha#99]
I have implemented ngx-recaptcha version 2 in my angular project. After checking I am not robot it is not popping up the images. Is there any extra setting i have to pass? Currently this is what i am using - 

```
<ngx-recaptcha2
      [siteKey]="siteKey"
      [size]="'Normal'"
      [hl]="'en'"
      [theme]="'Light'"
      [type]="'audio'"
      [useGlobalDomain]="false"
      formControlName="recaptcha"
      (load)="handleLoad()"
>
</ngx-recaptcha2>
```

**Comment by Enngage** [comment]
No idea, take a loot at the sample code and go from there -> https://github.com/Enngage/ngx-captcha/blob/master/demo/src/re-captcha-2-demo.component.ts
